name: Build (Pull Requests)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "**/*.md"

jobs:
  build-and-test:
    name: Build and Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      - run: echo "PACKAGE_VERSION=ci-$(date '+%Y%m%d-%H%M%S')+${GITHUB_SHA:0:6}" >> $GITHUB_ENV
      - run: echo "PACKAGE_VERSION=${PACKAGE_VERSION}"
      # Build
      - run: dotnet build ./src/GrpcWebSocketBridge.AspNetCore/ -c Release -p:VersionSuffix=${PACKAGE_VERSION}
      - run: dotnet build ./src/GrpcWebSocketBridge.Client/ -c Release -p:VersionSuffix=${PACKAGE_VERSION}
      # Test
      - run: dotnet test ./tests/GrpcWebSocketBridge.Tests/ -c Debug

  build-unity:
    if: ${{ ! github.event.pull_request.head.repo.fork }}
    strategy:
      matrix:
        unity: ["2021.3.22f1"]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Load secrets
        id: op-load-secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_PUBLIC }}
          UNITY_EMAIL: "op://GitHubActionsPublic/UNITY_LICENSE/username"
          UNITY_PASSWORD: "op://GitHubActionsPublic/UNITY_LICENSE/credential"
          UNITY_SERIAL: "op://GitHubActionsPublic/UNITY_LICENSE/serial"

      - uses: actions/checkout@v4
      # execute scripts/Export Package
      # /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod PackageExporter.Export
      - name: Export unitypackage
        uses: Cysharp/Actions/.github/actions/unity-builder@main
        env:
          UNITY_EMAIL: ${{ steps.op-load-secret.outputs.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ steps.op-load-secret.outputs.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ steps.op-load-secret.outputs.UNITY_SERIAL }}
        with:
          projectPath: src/GrpcWebSocketBridge.Client.Unity
          unityVersion: ${{ matrix.unity }}
          targetPlatform: StandaloneWindows
          buildMethod: PackageExporter.Export

      - uses: Cysharp/Actions/.github/actions/check-metas@main # check meta files
        with:
          directory: src/GrpcWebSocketBridge.Client.Unity

      # Store artifacts.
      - name: Get Version
        run: echo "GIT_TAG=$(cat src/GrpcWebSocketBridge.Client.Unity/Assets/Plugins/GrpcWebSocketBridge/package.json | jq -r '.version')" >> "$GITHUB_ENV"
      - uses: actions/upload-artifact@v4
        with:
          name: GrpcWebSocketBridge.${{ env.GIT_TAG }}.unitypackage
          path: ./src/GrpcWebSocketBridge.Client.Unity/GrpcWebSocketBridge.${{ env.GIT_TAG }}.unitypackage
