name: Build (Pull Requests)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "**/*.md"

jobs:
  build-and-test:
    name: Build and Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
      - run: echo "PACKAGE_VERSION=ci-$(date '+%Y%m%d-%H%M%S')+${GITHUB_SHA:0:6}" >> $GITHUB_ENV
      - run: echo "PACKAGE_VERSION=${PACKAGE_VERSION}"
      # Build
      - run: dotnet build ./src/GrpcWebSocketBridge.AspNetCore/ -c Release -p:VersionSuffix=${PACKAGE_VERSION}
      - run: dotnet build ./src/GrpcWebSocketBridge.Client/ -c Release -p:VersionSuffix=${PACKAGE_VERSION}
      # Test
      - run: dotnet test ./tests/GrpcWebSocketBridge.Tests/ -c Debug
